### ISSUE TITLE
Warrior doesn't start up

### ISSUE THREAD

**Issue by habi** [ArchiveTeam/seesaw-kit#103]
I downloaded a fresh VirtualBox and the appliance.
After importing the appliance and starting it up I see the following screenshot.

![screen shot 2017-11-04 at 21 21 36](https://user-images.githubusercontent.com/1651235/32409190-7a2729f6-c1a7-11e7-8789-7a05769e9fb3.PNG)

I then tried to quit the VM by `CTRL` + `C` and then the appliance seems to load correctly.
The browser is not able to load anything though, as can be seen in the second screenshot.

![screen shot 2017-11-04 at 21 23 21](https://user-images.githubusercontent.com/1651235/32409204-a4970ad0-c1a7-11e7-8254-eb1f4d112557.PNG)

VirtualBox Version 5.1.30 r118389 (Qt5.6.3) running on OS X 10.12.6 (16G29), with Safari Version 11.0 (12604.1.38.1.7)

**Comment by chfoo** [comment]
Hello, I pushed some updates to the warrior code. Rebooting the appliance should allow it to pick up the changes and update. Can you try again and let me know of the result?

**Comment by habi** [comment]
I seem to see that there's been an update (commit `86c7918`), but this doesn't seem to fix the problem.
Here's a small screencast of the startup procedure: https://youtu.be/LxwX2Ihyyz4

After briefly flashing the normal window, the warrior goes back to the 'terminal' view.
Once I press `CTRL`+ `C` it still seems to boot up correctly, but I cannot load it in Safari...

**Comment by chfoo** [comment]
Thanks for checking, I forgot to test on a fresh new appliance import. I pushed in another update. Can you check once again? You can also press `Alt+Right` and `Alt+Left` to see the other consoles too.

**Comment by habi** [comment]
All good now, the apliance is running as expected.
Thanks for the quick fix!
